# Generated by Django 4.2 on 2024-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_rename_senha_inscricao_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="inscriModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name="inscricao",
        ),
    ]
