# Generated by Django 4.2 on 2024-11-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_inscrimodel_delete_inscricao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="inscriModel",
            new_name="InscrModel",
        ),
    ]
