# Generated by Django 4.2 on 2024-11-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_rename_inscrimodel_inscrmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inscrmodel",
            old_name="password",
            new_name="password1",
        ),
        migrations.AddField(
            model_name="inscrmodel",
            name="username",
            field=models.CharField(default="null", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inscrmodel",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
