# Generated by Django 4.2 on 2024-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InforModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
